version: '3.9'

services:
  api:
    image: api
    build:
      dockerfile: Dockerfile.api
      context: .
    container_name: api
    env_file:
      - ./configs/.env
    restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - custom

  load:
    image: load
    build:
      dockerfile: Dockerfile.load
      context: .
    container_name: load
    env_file:
      - ./configs/.env
    restart: unless-stopped
    networks:
      - custom

  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - custom

  grafana:
    image: grafana/grafana:9.3.6
    container_name: grafana
    environment:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    ports:
      - 3000:3000
    volumes:
      - ./configs/grafana/automatic.yaml:/etc/grafana/provisioning/datasources/automatic.yaml
      - ./configs/grafana/main.yaml:/etc/grafana/provisioning/dashboards/automatic.yaml
      - ./configs/grafana/dashboard.json:/var/lib/grafana/dashboards/TheFourGoldenSignals/dashboard.json
    restart: unless-stopped

    networks:
      - custom

networks:
  custom:
    driver: bridge
